"use strict";
// Generated by https://quicktype.io
Object.defineProperty(exports, "__esModule", { value: true });
var Relationship;
(function (Relationship) {
    Relationship["None"] = "none";
})(Relationship = exports.Relationship || (exports.Relationship = {}));
