"use strict";
// Generated by https://quicktype.io
Object.defineProperty(exports, "__esModule", { value: true });
var AccountType;
(function (AccountType) {
    AccountType["User"] = "user";
})(AccountType = exports.AccountType || (exports.AccountType = {}));
var BlockStatus;
(function (BlockStatus) {
    BlockStatus["None"] = "none";
})(BlockStatus = exports.BlockStatus || (exports.BlockStatus = {}));
var BreweryType;
(function (BreweryType) {
    BreweryType["BrewPub"] = "Brew Pub";
    BreweryType["Cidery"] = "Cidery";
    BreweryType["MicroBrewery"] = "Micro Brewery";
    BreweryType["RegionalBrewery"] = "Regional Brewery";
})(BreweryType = exports.BreweryType || (exports.BreweryType = {}));
var CountryName;
(function (CountryName) {
    CountryName["UnitedStates"] = "United States";
})(CountryName = exports.CountryName || (exports.CountryName = {}));
var FirstName;
(function (FirstName) {
    FirstName["Chuck"] = "Chuck";
    FirstName["Gavin"] = "Gavin";
    FirstName["Jeff"] = "Jeff";
    FirstName["Nathan"] = "Nathan";
})(FirstName = exports.FirstName || (exports.FirstName = {}));
var LastName;
(function (LastName) {
    LastName["D"] = "D.";
    LastName["M"] = "M.";
    LastName["S"] = "S.";
})(LastName = exports.LastName || (exports.LastName = {}));
var LocationEnum;
(function (LocationEnum) {
    LocationEnum["Empty"] = "";
    LocationEnum["Rva"] = "RVA";
})(LocationEnum = exports.LocationEnum || (exports.LocationEnum = {}));
var Twitter;
(function (Twitter) {
    Twitter["Buskeycider"] = "@buskeycider";
    Twitter["Empty"] = "";
    Twitter["Southstbrewery"] = "@southstbrewery";
})(Twitter = exports.Twitter || (exports.Twitter = {}));
var VenueState;
(function (VenueState) {
    VenueState["Everywhere"] = "Everywhere";
    VenueState["Md"] = "MD";
    VenueState["Va"] = "VA";
})(VenueState = exports.VenueState || (exports.VenueState = {}));
var ParentCategoryID;
(function (ParentCategoryID) {
    ParentCategoryID["The4D4B7105D754A06376D81259"] = "4d4b7105d754a06376d81259";
    ParentCategoryID["The4E67E38E036454776Db1Fb3A"] = "4e67e38e036454776db1fb3a";
})(ParentCategoryID = exports.ParentCategoryID || (exports.ParentCategoryID = {}));
var PrimaryCategory;
(function (PrimaryCategory) {
    PrimaryCategory["NightlifeSpot"] = "Nightlife Spot";
    PrimaryCategory["Residence"] = "Residence";
})(PrimaryCategory = exports.PrimaryCategory || (exports.PrimaryCategory = {}));
var AppName;
(function (AppName) {
    AppName["UntappdForIPhoneV2"] = "Untappd for iPhone - (V2)";
})(AppName = exports.AppName || (exports.AppName = {}));
