"use strict";
// Generated by https://quicktype.io
Object.defineProperty(exports, "__esModule", { value: true });
var BreweryType;
(function (BreweryType) {
    BreweryType["BrewPub"] = "Brew Pub";
    BreweryType["Cidery"] = "Cidery";
    BreweryType["MacroBrewery"] = "Macro Brewery";
    BreweryType["MicroBrewery"] = "Micro Brewery";
    BreweryType["RegionalBrewery"] = "Regional Brewery";
})(BreweryType = exports.BreweryType || (exports.BreweryType = {}));
var CountryName;
(function (CountryName) {
    CountryName["Germany"] = "Germany";
    CountryName["Ireland"] = "Ireland";
    CountryName["Sweden"] = "Sweden";
    CountryName["UnitedStates"] = "United States";
})(CountryName = exports.CountryName || (exports.CountryName = {}));
