"use strict";
// Generated by https://quicktype.io
Object.defineProperty(exports, "__esModule", { value: true });
var BeerName;
(function (BeerName) {
    BeerName["DarkHollow"] = "Dark Hollow";
})(BeerName = exports.BeerName || (exports.BeerName = {}));
var BeerSlug;
(function (BeerSlug) {
    BeerSlug["BlueMountainBreweryDarkHollow"] = "blue-mountain-brewery-dark-hollow";
})(BeerSlug = exports.BeerSlug || (exports.BeerSlug = {}));
var BeerStyle;
(function (BeerStyle) {
    BeerStyle["StoutImperialDouble"] = "Stout - Imperial / Double";
})(BeerStyle = exports.BeerStyle || (exports.BeerStyle = {}));
var BreweryName;
(function (BreweryName) {
    BreweryName["BlueMountainBrewery"] = "Blue Mountain Brewery";
})(BreweryName = exports.BreweryName || (exports.BreweryName = {}));
var BreweryPageURL;
(function (BreweryPageURL) {
    BreweryPageURL["BlueMountainBrewery"] = "/BlueMountainBrewery";
})(BreweryPageURL = exports.BreweryPageURL || (exports.BreweryPageURL = {}));
var BrewerySlug;
(function (BrewerySlug) {
    BrewerySlug["BlueMountainBrewery"] = "blue-mountain-brewery";
})(BrewerySlug = exports.BrewerySlug || (exports.BrewerySlug = {}));
var Twitter;
(function (Twitter) {
    Twitter["Bluemtnbrewery"] = "bluemtnbrewery";
})(Twitter = exports.Twitter || (exports.Twitter = {}));
var CountryName;
(function (CountryName) {
    CountryName["UnitedStates"] = "United States";
})(CountryName = exports.CountryName || (exports.CountryName = {}));
var BreweryCity;
(function (BreweryCity) {
    BreweryCity["Afton"] = "Afton";
})(BreweryCity = exports.BreweryCity || (exports.BreweryCity = {}));
var State;
(function (State) {
    State["Everywhere"] = "Everywhere";
    State["Va"] = "VA";
})(State = exports.State || (exports.State = {}));
var AccountType;
(function (AccountType) {
    AccountType["User"] = "user";
})(AccountType = exports.AccountType || (exports.AccountType = {}));
var Relationship;
(function (Relationship) {
    Relationship["None"] = "none";
})(Relationship = exports.Relationship || (exports.Relationship = {}));
var AppName;
(function (AppName) {
    AppName["UntappdForAndroidV2"] = "Untappd for Android - (V2)";
    AppName["UntappdForIPhoneV2"] = "Untappd for iPhone - (V2)";
    AppName["UntappdWeb"] = "Untappd Web";
})(AppName = exports.AppName || (exports.AppName = {}));
var Bio;
(function (Bio) {
    Bio["BBCraftBeerGirlKatsCraftsWineInsta"] = "B&B Craft Beer Girl, Kats_Crafts&Wine -- Insta";
    Bio["BeerSure"] = "Beer? Sure!";
    Bio["Empty"] = "";
    Bio["The20LovibondAndUpSalud"] = "20\u00B0 Lovibond and up.  Salud!";
})(Bio = exports.Bio || (exports.Bio = {}));
var ParentCategoryID;
(function (ParentCategoryID) {
    ParentCategoryID["The4D4B7105D754A06374D81259"] = "4d4b7105d754a06374d81259";
    ParentCategoryID["The4D4B7105D754A06376D81259"] = "4d4b7105d754a06376d81259";
    ParentCategoryID["The4D4B7105D754A06378D81259"] = "4d4b7105d754a06378d81259";
    ParentCategoryID["The4D4B7105D754A06379D81259"] = "4d4b7105d754a06379d81259";
    ParentCategoryID["The4E67E38E036454776Db1Fb3A"] = "4e67e38e036454776db1fb3a";
})(ParentCategoryID = exports.ParentCategoryID || (exports.ParentCategoryID = {}));
var PrimaryCategory;
(function (PrimaryCategory) {
    PrimaryCategory["Food"] = "Food";
    PrimaryCategory["NightlifeSpot"] = "Nightlife Spot";
    PrimaryCategory["Residence"] = "Residence";
    PrimaryCategory["ShopService"] = "Shop & Service";
    PrimaryCategory["TravelTransport"] = "Travel & Transport";
})(PrimaryCategory = exports.PrimaryCategory || (exports.PrimaryCategory = {}));
