"use strict";
// Generated by https://quicktype.io
Object.defineProperty(exports, "__esModule", { value: true });
var BeerStyle;
(function (BeerStyle) {
    BeerStyle["StoutAmerican"] = "Stout - American";
    BeerStyle["StoutImperialDouble"] = "Stout - Imperial / Double";
    BeerStyle["StoutOatmeal"] = "Stout - Oatmeal";
})(BeerStyle = exports.BeerStyle || (exports.BeerStyle = {}));
var CountryName;
(function (CountryName) {
    CountryName["UnitedStates"] = "United States";
})(CountryName = exports.CountryName || (exports.CountryName = {}));
var VenueState;
(function (VenueState) {
    VenueState["Everywhere"] = "Everywhere";
    VenueState["Va"] = "VA";
})(VenueState = exports.VenueState || (exports.VenueState = {}));
var BreweryName;
(function (BreweryName) {
    BreweryName["BlueMountainBrewery"] = "Blue Mountain Brewery";
    BreweryName["MaineBeerCompany"] = "Maine Beer Company";
    BreweryName["NewHollandBrewing"] = "New Holland Brewing ";
    BreweryName["ProReNataBrewery"] = "Pro Re Nata Brewery";
    BreweryName["ThreeNotchDBrewing"] = "Three Notch'd Brewing";
})(BreweryName = exports.BreweryName || (exports.BreweryName = {}));
var BreweryPageURL;
(function (BreweryPageURL) {
    BreweryPageURL["BlueMountainBrewery"] = "/BlueMountainBrewery";
    BreweryPageURL["Mainebeercompany"] = "/mainebeercompany";
    BreweryPageURL["Newhollandbrew"] = "/newhollandbrew";
    BreweryPageURL["ProReNataBrewery"] = "/ProReNataBrewery";
    BreweryPageURL["ThreeNotchdBrewing"] = "/ThreeNotchdBrewing";
})(BreweryPageURL = exports.BreweryPageURL || (exports.BreweryPageURL = {}));
var BrewerySlug;
(function (BrewerySlug) {
    BrewerySlug["BlueMountainBrewery"] = "blue-mountain-brewery";
    BrewerySlug["MaineBeerCompany"] = "maine-beer-company";
    BrewerySlug["NewHollandBrewing"] = "new-holland-brewing";
    BrewerySlug["ProReNataBrewery"] = "pro-re-nata-brewery";
    BrewerySlug["ThreeNotchDBrewing"] = "three-notch-d-brewing";
})(BrewerySlug = exports.BrewerySlug || (exports.BrewerySlug = {}));
var Twitter;
(function (Twitter) {
    Twitter["Bluemtnbrewery"] = "bluemtnbrewery";
    Twitter["Mainebeerco"] = "mainebeerco";
    Twitter["NewHollandBrew"] = "NewHollandBrew";
    Twitter["PRNBrewery"] = "PRNBrewery";
    Twitter["ThreeNotchdBeer"] = "ThreeNotchdBeer";
})(Twitter = exports.Twitter || (exports.Twitter = {}));
var BreweryCity;
(function (BreweryCity) {
    BreweryCity["Afton"] = "Afton";
    BreweryCity["Charlottesville"] = "Charlottesville";
    BreweryCity["Crozet"] = "Crozet";
    BreweryCity["Freeport"] = "Freeport";
    BreweryCity["Holland"] = "Holland";
})(BreweryCity = exports.BreweryCity || (exports.BreweryCity = {}));
var BreweryState;
(function (BreweryState) {
    BreweryState["Me"] = "ME";
    BreweryState["Mi"] = "MI";
    BreweryState["Va"] = "VA";
})(BreweryState = exports.BreweryState || (exports.BreweryState = {}));
var AppName;
(function (AppName) {
    AppName["UntappdForAndroidV2"] = "Untappd for Android - (V2)";
    AppName["UntappdForIPhoneV2"] = "Untappd for iPhone - (V2)";
})(AppName = exports.AppName || (exports.AppName = {}));
var Bio;
(function (Bio) {
    Bio["BBCraftBeerGirlKatsCraftsWineInsta"] = "B&B Craft Beer Girl, Kats_Crafts&Wine -- Insta";
    Bio["BeerSure"] = "Beer? Sure!";
    Bio["Empty"] = "";
})(Bio = exports.Bio || (exports.Bio = {}));
var LocationEnum;
(function (LocationEnum) {
    LocationEnum["AlexandriaVA"] = "Alexandria,VA";
    LocationEnum["Empty"] = "";
    LocationEnum["LivoniaMI"] = "Livonia, MI";
})(LocationEnum = exports.LocationEnum || (exports.LocationEnum = {}));
